# Generated by Django 5.0 on 2023-12-17 12:40

import movie.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "year_released",
                    models.IntegerField(
                        default=0,
                        help_text="YYYY",
                        validators=[movie.models.year_validator],
                    ),
                ),
                ("description", models.CharField(max_length=2000)),
                (
                    "poster",
                    models.ImageField(blank=True, null=True, upload_to="movie/posters"),
                ),
                (
                    "rating",
                    models.FloatField(
                        blank=True, default=0.0, help_text="0.0 to 10.0", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "genre",
                    models.ManyToManyField(related_name="movie", to="movie.genre"),
                ),
            ],
            options={
                "verbose_name": "Movie",
                "verbose_name_plural": "Movies",
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
            },
        ),
    ]
